### ISSUE TITLE
Product page shows duplicate topics

### ISSUE THREAD

**Issue by zod000** [rkalla/imgscalr#121]
Example:
https://www.etesters.com/product/8E840F11-0069-1F4E-A02D-39AE20D8FA0D/

Optical Fiber shows twice.

**Comment by krichter722** [comment]
Please explain how this is related to the development of imgscalr.

**Comment by zod000** [comment]
This issue was posted to a private repo, I have no idea how it also appears here.  I apologize for any inconvenience.
