### ISSUE TITLE
Resized JPG image gets Pink background

### ISSUE THREAD

**Issue by nickrussler** [rkalla/imgscalr#82]
I resized several images from this website:

http://www.teknosa.com

For example the attached file.

I resized the image(s) with imgscalr and the result was broken (pink background).

Also replicable with the online demo: 
http://imgscalr.com/

Input Image:
![bugged](https://f.cloud.github.com/assets/1096768/35250/09d7136a-51c1-11e2-8732-7339d8e3cf5e.jpg)

Bugged Result:
![GwgGKaAuv-M](https://f.cloud.github.com/assets/1096768/35254/44f39e28-51c1-11e2-8155-c5fe9fa33131.jpg)

**Comment by tootsweet** [comment]
@nickrussler / thank you very much, your code did the trick.
